<?php
return [
    'DB_HR' => env('DB_DATABASE_HR_BY_NAME', 'ERP_HR'),
    'DB_Logistic' => env('DB_DATABASE_Logistic_BY_NAME', 'ERP_Logistic'),
    'DB_Inventory' => env('DB_DATABASE_Inventory_BY_NAME', 'ERP_Inventory'),
    'DB_SAD' => env('DB_DATABASE_SAD_BY_NAME', 'ERP_SAD'),
    'DB_Apps' => env('DB_DATABASE_Apps_BY_NAME', 'ERP_Apps'),
    'DB_Accounts' => env('DB_DATABASE_Accounts_BY_NAME', 'ERP_Accounts'),
    'DB_Global' => env('DB_DATABASE_GLOBAL_BY_NAME', 'ERP_Global'),
    'DB_Role' => env('DB_DATABASE_ROLE_BY_NAME', 'DB_Role'),
    'DB_Asset' => env('DB_DATABASE_Asset_BY_NAME', 'ERP_Asset'),
    'DB_ASLL' => env('DB_DATABASE_ASLL_BY_NAME', 'DB_ASLL'),
    'DB_Remote' => env('DB_DATABASE_Remote_BY_NAME', 'ERP_Remote'),
    'DB_PSD' => env('DB_DATABASE_PSD_BY_NAME', 'DB_PSD'),
    'DB_CRM' => env('DB_DATABASE_CRM_BY_NAME', 'DB_CRM'),
    'DB_AG_FuelLog' => env('DB_DATABASE_AG_FuelLog_BY_NAME', 'DB_AG_FuelLog'),
    'DB_BrandTradeMkt' => env('DB_DATABASE_BrandTradeMkt_BY_NAME', 'DB_BrandTradeMkt'),
    'DB_Payment' => env('DB_DATABASE_Payment_BY_NAME', 'ERP_Payment'),
    'DB_iApps' => env('DB_DATABASE_iApps_BY_NAME', 'DB_iApps'),
    'DB_AFBLSMSServer' => env('DB_DATABASE_AFBLSMSServer_BY_NAME', 'DB_AFBLSMSServer'),
];
